ebl-issuance/src/main/resources/standards/eblissuance/messages/eblissuance-v30-request.json
ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/models/CarrierShippingInstructions.java
ebl/src/main/resources/standards/ebl/schemas/ebl-api-v30.json

Also added a conditional validation to catch regressions.

DT-826: Remove `commoditySubreference` from TD

---

spring-boot/src/main/java/org/dcsa/conformance/springboot/ConformanceTomcatConfig.java

...when left unspecified for application/json

DT-903 Tomcat no longer appending the wrong charset

---

pint/src/main/java/org/dcsa/conformance/standards/eblinterop/PintComponentFactory.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/PintAction.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/ReceiverSupplyScenarioParametersAndStateSetupAction.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/SenderSupplyScenarioParametersAction.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/crypto/PayloadSignerFactory.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/crypto/SignatureVerifierWithKey.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/ReceiverScenarioParameters.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/SenderScenarioParameters.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/TDReceiveState.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/party/PintReceivingPlatform.java
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/party/PintSendingPlatform.java

Per George's request in DT-875, the key exchange is done via input prompts.

DT-875: Support key exchange via scenario parameters

---

ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/checks/IssuanceChecks.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/models/CarrierShippingInstructions.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblCarrier.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblShipper.java
ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-beta-2-2c2u1e.json
ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-beta-2-2c2u2e.json
ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-beta-2-amf.json
ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-beta-2-dg.json
ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-beta-2-request.json
ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-beta-2-soc-references.json
ebl/src/main/resources/standards/ebl/schemas/ebl-api-3.0.0-beta-2.json
ebl/src/main/resources/standards/ebl/schemas/ebl-notification-3.0.0-beta-2.json
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/checks/PintChecks.java

Also performed a series of "unrelated" changes as a consequence of the schema changes. This happened because a lot of schema changes were done without the conformance toolkit being kept up to speed unfortunately.

DT-973: Change "Country" to "Country Code"

---

core/src/main/java/org/dcsa/conformance/core/check/ResponseStatusCheck.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/action/EblAction.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/action/StateChangingSIAction.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/action/UC1_Shipper_SubmitShippingInstructionsAction.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/action/UC3_Shipper_SubmitUpdatedShippingInstructionsAction.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/action/UC5_Shipper_CancelUpdateToShippingInstructionsAction.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/action/UC7_Shipper_ApproveDraftTransportDocumentAction.java

This will not close DT-1217 since the API specs have not been updated, so it might be wrong.

DT-1217: Guess of which API calls will allow 202

---

.github/workflows/master.yml

STNG-145 Fix non-PR build: do not use PR parameters

---

.github/workflows/deploy-to-aws.yml
.github/workflows/master.yml

Note: branched from master, in order to get it visual in GitHub.
The last step (deploy) is disabled, since I'd like to see it working fine first.

STNG-17 Deploy to AWS from a GitHub Action

---

ebl/src/main/java/org/dcsa/conformance/standards/ebl/crypto/PayloadSignerFactory.java
spring-boot/src/test/java/org/dcsa/conformance/manual/ManualEBlIssuanceTest.java

* Removed some unused methods
Niels, I removed some unused methods.. ok with that?

STNG-129 Add eBL Issuance Manual Test on the first scenario

---

.github/workflows/deploy-to-aws.yml

* Disabled the manual input mode (for now)

STNG-17 Make AWS deployments on dev branch run automatically

---

booking/pom.xml
cdk/pom.xml
commercial-schedules/pom.xml
core/pom.xml
ebl-issuance/pom.xml
ebl-surrender/pom.xml
ebl/pom.xml
jit/pom.xml
lambda/pom.xml
ovs/pom.xml
pint/pom.xml
pom.xml
sandbox/pom.xml
spring-boot/pom.xml
tnt/pom.xml

* Introduce dependencyManagement section
* Define submodule versions only in the parent pom
* Enhance parent pom with project information

Improve Maven structure of whole project

---

.github/workflows/master.yml
README.md
lambda/README.md

Just a start.. please add suggestions, or edit the file, to improve it.

STNG-143 Add README.md file to explain this project

---

.github/workflows/deploy-to-aws.yml

Prevents our Dev environment using `localhost:8080` configuration.. 🤔

STNG-20 Fix missing environment variable passed on to Angular build

---

booking/pom.xml
commercial-schedules/pom.xml
core/pom.xml
core/src/main/java/org/dcsa/conformance/core/check/JsonSchemaValidator.java
core/src/test/java/org/dcsa/conformance/core/check/JsonSchemaValidatorTest.java
core/src/test/resources/examples/booking-request.json
core/src/test/resources/schemas/booking-api-v20.json
ebl-issuance/pom.xml
ebl-surrender/pom.xml
ebl/pom.xml
ovs/pom.xml
pom.xml
tnt/pom.xml

Also upgrade the library a bit. Towards higher version numbers was not easily possible. 
Cleanup up duplicate dependency definitions.

STNG-148 JSON schema validation logs 3 warnings every time

---

webui/package-lock.json

6 moderate vulns left, which `npm audit fix` can not solve atm.

STNG-20 Upgrade WebUI packages once more

---

.github/workflows/deploy-to-aws.yml

* They were reverted by merging master to dev

STNG-20 Re-apply changes from dev branch

---

ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-request.json

The code was already correct, but only Description of Goods was covered.

DT-1599: Add a payload with shipping marks

---

.github/workflows/deploy-to-aws.yml
.github/workflows/master.yml
.github/workflows/webui-testing.yml
booking/pom.xml
pom.xml
spring-boot/pom.xml
spring-boot/src/test/java/org/dcsa/conformance/frontend/SeleniumTest.java
spring-boot/src/test/java/org/dcsa/conformance/manual/ManualTestBase.java
webui/src/app/pages/create-sandbox/create-sandbox.component.html
webui/src/app/pages/edit-sandbox/edit-sandbox.component.html
webui/src/app/pages/environment/environment.component.html
webui/src/app/pages/login/login.component.html
webui/src/app/pages/sandbox/sandbox.component.html
webui/src/app/pages/scenario/scenario.component.html

Run Web UI tests with Selenium, using Chrome browser and NPM, to test if the Manual test scenario's still work fine. 
Some standards can not be enabled, because of outstanding issues (encountered on the STNG-171 issue). 
Selenium best-practice question raised to be discussed later.

STNG-181 Add Manual Testing through browser (with Selenium)

---

commercial-schedules/src/main/resources/standards/commercialschedules/schemas/commercialschedules-api-v10.json

Updated CS conformance with the latest API schema

APCV-1377-Updated the CS schema with the latest one

---

spring-boot/src/main/java/org/dcsa/conformance/springboot/ConformanceApplication.java
spring-boot/src/test/java/org/dcsa/conformance/manual/ManualTestBase.java
spring-boot/src/test/java/org/dcsa/conformance/springboot/ConformanceApplicationTest.java

* Speed improvements: 24 minutes -> 5 minutes on CI test run

STNG-8 Improve running speed of auto tests and manual tests

---

core/src/main/java/org/dcsa/conformance/core/party/ConformanceParty.java
core/src/main/java/org/dcsa/conformance/core/toolkit/IOToolkit.java
sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceSandbox.java

This reverts commit 154902245c3b5b6d2de735f50747589aea09d3b9.
Relates to: STNG-8 Reuse HttpClient (#191)

SD-1517 Apply again: Reuse HTTP client

---

cdk/pom.xml
ebl-issuance/pom.xml
ebl/pom.xml
lambda/pom.xml
pom.xml
sandbox/pom.xml
spring-boot/pom.xml
webui/package-lock.json

Update all Java libraries and WebUI libraries

---

ebl-issuance/src/main/resources/standards/eblissuance/schemas/EBL_ISS_v3.0.0.yaml
ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblShipper.java
ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-negotiable-bl.json
ebl/src/main/resources/standards/ebl/schemas/EBL_v3.0.0.yaml

[SD-1501](https://dcsa.atlassian.net/browse/SD-1501)
- Updated the latest schema for EBL-ISS and EBL
- Added atleast one identifying code mandatory for consignee and endorsee in EBL and EBL-ISS
[SD-1501]: https://dcsa.atlassian.net/browse/SD-1501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SD-1501-EBL-TD-atleast one identifyingcode mandatory

---

booking/src/main/java/org/dcsa/conformance/standards/booking/checks/BookingChecks.java
booking/src/test/java/org/dcsa/conformance/standards/booking/checks/BookingChecksTest.java

…modities.
___
Enhancement, Tests
___
- Introduced a new validation check for cargo gross weight conditions in the `BookingChecks` class.
- The check ensures that if the `cargoGrossWeight` is missing or null, each commodity must have its own `cargoGrossWeight`.
- Integrated the new check into the existing validation framework to ensure it is executed as part of the booking checks.
- Developed comprehensive unit tests to validate the new logic, covering both valid and invalid scenarios.
___
<tr>
<td>
<details>
<summary><strong>BookingChecks.java</strong><dd><code>Add cargo gross weight validation check in BookingChecks</code>&nbsp; </dd></summary>
<hr> …

SD-650 Check cargoGrossWeight conditions in RE and its subsequent commodities

---

pint/src/main/resources/standards/pint/messages/pint-3.0.0-transport-document.json
pint/src/main/resources/standards/pint/schemas/EBL_PINT_v3.0.0.yaml

Enhancement, Documentation
___
- Added `identifyingCodes` to `shipper` and `consignee` in transport document JSON.
- Updated OpenAPI YAML with new attributes and conditions:
- Introduced `controlTrackingRegistry` for CTR URI in `EnvelopeTransferChainEntry`.
- Added mandatory `identifyingCodes` for `Consignee`, `Endorsee`, and `Shipper`.
- Clarified conditions for various fields like `declaredValueCurrency`, `temperatureUnit`, and `airExchangeUnit`.
- Enhanced documentation for API usage, error codes, and digital signatures.
- Fixed formatting, typos, and improved consistency in descriptions.
___
<tr>
<td>
<details> …

Update the EBL_PINT spec to match current swagger spec

---

ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblShipper.java
ebl/src/test/java/org/dcsa/conformance/standards/ebl/checks/EBLChecksTest.java

Bug fix, Tests
___
- Fixed `sendToPlatform` validation logic in `EBLChecks`.
- Updated `EblShipper` to handle `sendToPlatform` for BOL documents.
- Added unit tests for `sendToPlatform` conditional check in `EBLChecksTest`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>EBLChecks.java</strong><dd><code>Fix `sendToPlatform` validation logic in `EBLChecks`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
<li>Made <code>SEND_TO_PLATFORM_CONDITIONAL_CHECK</code> accessible by removing <code>private</code> <br>modifier.<br> <li> Updated validation logic for …

SD-1931 Fix EBL conformance check issue

---

.github/workflows/deploy-to-aws.yml
.github/workflows/master.yml
.github/workflows/webui-testing.yml

* For consistency with AWS Lambda runs

SD-1946 Migrate to Amazon Corretto JVM

---

jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitPartyHelper.java

initialize timestamps node at first usage

SD-1895 Fix WebUI tests of JIT 2.0

---

lambda/pom.xml
lambda/src/main/java/org/dcsa/conformance/lambda/LambdaToolkit.java

Reverts dcsaorg/Conformance-Gateway#257

Revert "SD-1628 Migrate to AWS SDK 2.0"

---

webui/angular.json

Fixes deployment of UI packages, in the previous commit on PR #273

SD-2027 Fix Web UI build, by increasing maximumWarning and maximumError

---

booking/src/main/java/org/dcsa/conformance/standards/booking/party/DynamicScenarioParameters.java
core/src/main/java/org/dcsa/conformance/core/AbstractComponentFactory.java
core/src/main/java/org/dcsa/conformance/core/party/ConformanceParty.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/DynamicScenarioParameters.java
jit/src/main/java/org/dcsa/conformance/standards/jit/JitScenarioListBuilder.java
jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitGetAction.java
jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitPortCallAction.java
jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitPortCallServiceAction.java
jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitTerminalCallAction.java
jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitTimestampAction.java
jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitConsumer.java
jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitRole.java
sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceSandbox.java
sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceWebuiHandler.java

* Remove confusion: Provider and Consumer point to: Port Call Service Provider and Port Call Service Consumer.
* Also removed `@NonNull` where it had no effect

SD-2049 JIT: Add Service to Provider and Consumer

---

booking/src/main/java/org/dcsa/conformance/standards/booking/party/BookingCarrier.java
booking/src/main/resources/standards/booking/instructions/prompt-shipper-uc9.md

Booking: correct error message on cancellation in UC9 and improve prompt
* Prevent NPE as well, by reverting the arguments
Please let me know if the texts should be improved even more.

SD-2071 Booking: correct error message on cancellation in UC9 and improve prompt

---

jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitWrongTimestampAction.java
jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitPartyHelper.java
jit/src/main/resources/standards/jit/instructions/prompt-process-oob-request.md
jit/src/main/resources/standards/jit/schemas/JIT_v2.0.0.yaml

Some pending improvements: update schema to current version of OpenAPI. Update OOB text, to better match situations.

SD-160 JIT: Update schema; improve OOB instruction

---

webui/package-lock.json

Finally, it is possible to fix `esbuild` 😄 also fixes `prismjs`. 
After this PR: `found 0 vulnerabilities`

SD-2053 Upgrade Web UI libraries, fixing esbuild and prismjs vulnerabilities

---

ovs/src/main/java/org/dcsa/conformance/standards/ovs/OvsScenarioListBuilder.java
ovs/src/main/resources/standards/ovs/messages/ovs-300-response.json

Bug fix
___
- Fix FACS location type scenarios to include required UNLOCODE
- Update test parameters to combine location and facility codes
- Add new test data with proper FACS location structure
___
```mermaid
flowchart LR
A["Scenario Parameters"] --> B["Add UNLOCODE to FACS"]
B --> C["Updated Test Data"]
C --> D["Valid FACS Location"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>OvsScenarioListBuilder.java</strong><dd><code>Update scenario parameters for FACS locations</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …

SD-2233: Fix 2 scenarios related to FACS location type missing UNLOCODE

---

ebl/src/main/java/org/dcsa/conformance/standards/ebl/EblScenarioListBuilder.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/action/ShipperGetTransportDocumentErrorAction.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblCarrier.java
ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblShipper.java
ebl/src/main/resources/standards/ebl/instructions/prompt-shipper-get-transport-document-error-scenario.md
ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-error-message.json

Enhancement
___
- Add error scenario for transport document retrieval
- Implement 404 error response with proper schema validation
- Create new action for testing invalid document references
- Update carrier to return structured error responses
___
```mermaid
flowchart LR
A["Shipper"] -- "GET /transport-documents/{invalid-ref}" --> B["Carrier"]
B -- "404 Error Response" --> A
C["Error Schema Validator"] -- "validates" --> B
D["Error Template"] -- "generates" --> B
```
<tr>
<td>
<details>
<summary><strong>EblScenarioListBuilder.java</strong><dd><code>Add error scenario configuration and …

SD-2372: implement error scenario for td

---

booking/src/main/java/org/dcsa/conformance/standards/booking/action/UC9_Shipper_CancelBookingAmendment.java
booking/src/main/java/org/dcsa/conformance/standards/booking/checks/BookingChecks.java
booking/src/test/java/org/dcsa/conformance/standards/booking/checks/BookingChecksTest.java

Bug fix, Enhancement
___
- Remove booking amendment cancellation validation logic
- Fix document party function uniqueness validation
- Improve shipper minimum request fields validation
- Clean up booking state validation checks
___
```mermaid
flowchart LR
A["UC9 Action"] --> B["Remove Amendment Validation"]
C["BookingChecks"] --> D["Fix Document Party Validation"]
C --> E["Improve Shipper Validation"]
C --> F["Clean State Checks"]
G["Tests"] --> H["Add Document Party Tests"]
G --> I["Remove Amendment Tests"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>UC9_Shipper_CancelBookingAmendment.java</strong><dd><cod …

SD-2415: Fixed booking checks

---

booking/src/main/resources/standards/booking/schemas/BKG_v2.0.0.yaml

Enhancement
___
- Update API version from 2.0.0 to 2.0.2
- Add new transport document references array property
- Add routing reference for predefined routes
- Add pre/on carriage mode of transport fields
- Deprecate single transport document reference property
___
```mermaid
flowchart LR
A["API v2.0.0"] --> B["API v2.0.2"]
B --> C["New Transport Document References"]
B --> D["Routing Reference Support"]
B --> E["Carriage Mode Fields"]
B --> F["Deprecated Properties"]
```
<tr>
<td>
<details>
<summary><strong>BKG_v2.0.0.yaml</strong><dd><code>Major API schema update with new transport …

SD-2334: update booking schema

---

booking/src/main/java/org/dcsa/conformance/standards/booking/checks/BookingChecks.java
booking/src/test/java/org/dcsa/conformance/standards/booking/checks/BookingChecksTest.java

Enhancement
___
- Add mandatory `shipmentCutOffTimes` validation for confirmed bookings
- Update confirmed booking states to exclude COMPLETED and DECLINED
- Implement comprehensive test coverage for booking field validation
- Refactor validation logic with improved error handling
___
```mermaid
flowchart LR
A["Booking Status Check"] --> B["CONFIRMED or PENDING_AMENDMENT?"]
B --> C["Validate Required Fields"]
C --> D["confirmedEquipments"]
C --> E["transportPlan"]
C --> F["shipmentCutOffTimes"]
D --> G["Validation Result"]
E --> G
F --> G
```
<tr>
<td>
<details> …

Sd 2472 mandatory cutoff times
