dcsaorg/Conformance-Gateway

- core/src/main/java/org/dcsa/conformance/core/Util.java
- core/src/main/java/org/dcsa/conformance/core/check/JsonSchemaValidator.java
- core/src/main/java/org/dcsa/conformance/core/party/ActionPromptsQueue.java
- core/src/main/java/org/dcsa/conformance/core/party/ConformanceParty.java
- core/src/main/java/org/dcsa/conformance/core/report/ConformanceReport.java
- core/src/main/java/org/dcsa/conformance/core/scenario/ConformanceAction.java
- core/src/main/java/org/dcsa/conformance/core/scenario/ConformanceScenario.java
- core/src/main/java/org/dcsa/conformance/core/state/MemorySortedPartitionsNonLockingMap.java
- core/src/main/java/org/dcsa/conformance/core/toolkit/JsonToolkit.java
- core/src/main/java/org/dcsa/conformance/core/traffic/ConformanceExchange.java
- core/src/main/java/org/dcsa/conformance/core/traffic/ConformanceMessage.java
- core/src/main/java/org/dcsa/conformance/core/traffic/ConformanceMessageBody.java
- core/src/main/java/org/dcsa/conformance/core/traffic/ConformanceRequest.java
- core/src/main/java/org/dcsa/conformance/core/traffic/ConformanceResponse.java
- core/src/main/java/org/dcsa/conformance/core/traffic/TrafficRecorder.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceOrchestrator.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceSandbox.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceWebRequest.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceWebuiHandler.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/configuration/SandboxConfiguration.java
- spring-boot/src/main/java/org/dcsa/conformance/springboot/ConformanceApplication.java
In a single `auto` run for eBL, the `new ObjectMapper()` was profiled to take ~60s CPU time (across all threads).  This change sadly does not translate directly into a ~60s wall time improvement.
However, it is was trivial to fix and remove the `new ObjectMapper()` line from the profiling.
> Avoid creating object mappers all the time

- core/src/main/java/org/dcsa/conformance/core/party/ActionPromptsQueue.java
- core/src/main/java/org/dcsa/conformance/core/party/ConformanceParty.java
- core/src/main/java/org/dcsa/conformance/core/scenario/ConformanceScenario.java
- core/src/main/java/org/dcsa/conformance/core/scenario/ScenarioListBuilder.java
- core/src/main/java/org/dcsa/conformance/core/state/StatefulExecutor.java
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/EblScenarioListBuilder.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceOrchestrator.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceSandbox.java
Note: Locally I had to tweak the `MemorySortedPartitionsLockingMap` time outs to view the report. I have not included the changes to these time outs, because I feel it is the wrong solution. Loading the report should not take that long.
> DT-862 [2/2]: Add abuse-cases test scenarios to eBL

- spring-boot/src/main/java/org/dcsa/conformance/springboot/ConformanceApplication.java
- spring-boot/src/test/java/org/dcsa/conformance/springboot/ConformanceApplicationTest.java
- spring-boot/src/test/java/org/dcsa/conformance/springboot/ConformanceBasicAPITest.java
- spring-boot/src/test/resources/application.properties
and: Remove Carrier1Prompt and Platform1Prompt tests. Disable confusing API tests, which throw useless timeouts.
> STNG-131 Re-enable tests of sandboxIds

- core/src/main/java/org/dcsa/conformance/core/AbstractComponentFactory.java
- core/src/main/java/org/dcsa/conformance/core/scenario/ConformanceScenario.java
- core/src/main/java/org/dcsa/conformance/core/scenario/ScenarioListBuilder.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceOrchestrator.java
Move the `ConformanceScenario` creation into the `AbstractComponantFactory` and reduce visbility of `createModuleScenarioListBuilders`. This will enable us to use different scenarion creation methods for different standards.
In the `ConformanceOrchestrator`, reduce the typing of `scenariosByModuleName` to `List<ConformanceScenario>` from `ArrayList<...>`. The actual list is not used externally and internally the orchestrator will always just iterate over it via stream or for-each loops. Given there is no "random access" accessing, then any `List`-type will do. This in turn will enable more flexibility for the scenarion building code to choose which list is used.
> Refactor conformance scenario creation

- .github/workflows/master.yml
* Also enable SonarCloud PR decoration, by adding sonar.pullrequest.provider
* No need to specify PR base branches; all PRs are applicable
> STNG-145 Add SonarCloud Quality Gate check to GitHub pipeline

- commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/CsScenarioListBuilder.java
- commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/action/CsGetPortSchedulesAction.java
- commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/action/CsGetRoutingsAction.java
- commercial-schedules/src/main/java/org/dcsa/conformance/standards/cs/action/CsGetVesselSchedulesAction.java
-Fix for incorrect prompt and updated the GET actions title for pagination scenarios
> APCV-1367 and APCV-1268 - CS conformance issue fix

- README.md
- pom.xml
- spring-boot/pom.xml
Current description does not work. 
Note: Spring Boot is not added as a normal dependency, only a build plugin is added to the root project.
> Fix build instructions: start Spring Boot from command-line

- ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
The issue is about copies because I swapped the copies and originals issue (the fix for other issue was already reviewed and merged despite being for the opposite attributes). Keeping the confusing total, this commits to the issue swapped problem.
> DT-1657: Improve validation related to number of copies/originals

- .github/workflows/deploy-to-aws.yml
- .github/workflows/master.yml
- .github/workflows/webui-testing.yml
- pom.xml
- spring-boot/src/test/java/org/dcsa/conformance/frontend/AWSEnvironmentTest.java
- spring-boot/src/test/java/org/dcsa/conformance/frontend/SeleniumTest.java
- spring-boot/src/test/java/org/dcsa/conformance/frontend/SeleniumTestBase.java
- spring-boot/src/test/java/org/dcsa/conformance/manual/ManualScenarioTest.java
- spring-boot/src/test/java/org/dcsa/conformance/manual/ManualTestBase.java
Created test `AWSEnvironmentTest` which runs Ebl, Conformance TD-only, Carrier fully end-to-end. 
Created the SeleniumTestBase for code reuse. It does not start Spring Boot itself. 
Sorry for the refactoring and changes in the same PR.. which makes it harder to see the changes.
> STNG-165 Run one scenario in AWS dev fully end-to-end

- booking/src/main/java/org/dcsa/conformance/standards/booking/party/BookingCarrier.java
- core/src/main/java/org/dcsa/conformance/core/party/ConformanceParty.java
- core/src/main/java/org/dcsa/conformance/core/toolkit/IOToolkit.java
- sandbox/src/main/java/org/dcsa/conformance/sandbox/ConformanceSandbox.java
Reuse it, to avoid creating many threads and expensive objects.
Separated 2 different commits:
1. HttpClient improvements
2. Logging changes.
> STNG-8 Reuse HttpClient

- spring-boot/src/test/java/org/dcsa/conformance/manual/ManualTestBase.java
Slower systems need more time after a Notify Action and Complete Action, apparently. The clean sandbox state checking was not enough.
> STNG-8 Add verification and some delay to give actions time to complete

- booking/src/main/java/org/dcsa/conformance/standards/booking/checks/BookingDataSets.java
- core/pom.xml
- core/src/main/java/org/dcsa/conformance/core/check/KeywordDataset.java
- core/src/main/java/org/dcsa/conformance/core/check/KeywordDatasets.java
- core/src/main/java/org/dcsa/conformance/core/check/VersionedKeywordDataset.java
- core/src/test/java/org/dcsa/conformance/core/check/KeywordDatasetTest.java
- core/src/test/resources/convert-csv-file.csv
- core/src/test/resources/convert-csv-file_wrong.csv
- ebl/pom.xml
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EblDatasets.java
- spring-boot/src/test/java/org/dcsa/conformance/manual/ManualScenarioTest.java
STNG-25 Replace OpenCSV by plain Java
* OpenCSV is having security issues
* The OpenCSV library is not needed, since we're dealing with simple CSV files atm.
* Added common-text dependency for StringEscapeUtils (not available transitively anymore)
> STNG-25 Replace OpenCSV by plain Java

- .github/workflows/deploy-to-aws.yml
- spring-boot/src/test/java/org/dcsa/conformance/frontend/SeleniumTest.java
- spring-boot/src/test/java/org/dcsa/conformance/frontend/SeleniumTestBase.java
Some 'Deploy to AWS' tasks failed, after a PR was merged. This is caused by cold starts of Lambda, after a fresh deployment. Giving it a bit more time to warm up.
> STNG-165 Fix slow Lambda startup

- lambda/pom.xml
- pom.xml
STNG-199 Pin dependencies to recent versions; prevent deviation in the project
* Use bom imports where possible
* Moved Lambda part to parent, since it could used elsewhere too
> STNG-199 Pin dependencies to recent versions

- ebl/src/main/java/org/dcsa/conformance/standards/ebl/EblScenarioListBuilder.java
- spring-boot/src/test/java/org/dcsa/conformance/frontend/SeleniumTestBase.java
- spring-boot/src/test/java/org/dcsa/conformance/manual/ManualTestBase.java
STNG-210 After sending handleActionInput, check if conformance level progresses
* Also check for `inputRequired`, to stop waiting and proceed to the next step
* Workaround for EBL Issuance is in place, until that standard is revisited. 
Also added some useful sandbox details, if a Selenium tests fails on conformance issues (did not happen before, so just saw that this is missing).
> STNG-210 After sending handleActionInput, check if conformance level progresses

- spring-boot/src/test/java/org/dcsa/conformance/manual/ManualTestBase.java
Previous PR on STNG-210 improves how the manual tests are run, but they accidentally hide non-conformant logging. This adds it back in the logs.
> STNG-210 Improve failure logging on running Manual Tests.

- ebl/pom.xml
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/crypto/PayloadSignerFactory.java
The real issue was the header used `RSA `, when it should not have. However, I also changed the code to use Bouncycastle's PEM parser and writer to delegate some of the code to a library.
> SD-1775: Issues with parsing the provided public key

- ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EblDatasets.java
- ebl/src/test/java/org/dcsa/conformance/standards/ebl/checks/EBLChecksTest.java
enhancement, tests
___
- Introduced validation for consignment items reference types to ensure they match known dataset keywords.
- Refactored the code to replace string literals with constants for better maintainability and consistency.
- Added a new dataset for consignment items reference types in `EblDatasets`.
- Enhanced test coverage by adding tests for the new consignment items reference types validation.
- Refactored test setup in `EBLChecksTest` to use a helper method for creating root nodes.
___
<tr>
<td>
<details>
<summary><strong>EBLChecks.java</strong><dd><code>Enhance validation and refactor constants usage</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> SD-508-Shipper and consignee po reference

- ebl-issuance/src/main/resources/standards/eblissuance/schemas/EBL_ISS_v3.0.0.yaml
- ebl/src/main/resources/standards/ebl/schemas/EBL_v3.0.0.yaml
enhancement, documentation
___
- Updated the eBL Issuance API documentation to consistently use the term `eBL` instead of `EBL`.
- Improved the contact and changelog information for better clarity and accessibility.
- Clarified the conditions for specifying the location in the `PlaceOfIssue` section.
- Corrected a typo in the description of the `Import License` reference number.
- Updated titles in the `Document Parties` sections to provide more context.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>EBL_ISS_v3.0.0.yaml</strong><dd><code>Update and clarify eBL Issuance API documentation and terminology</code></dd></summary>
<hr> …
> SD-350 Update placeofissue-ebl

- ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EblDatasets.java
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-request.json
- ebl/src/test/java/org/dcsa/conformance/standards/ebl/checks/EBLChecksTest.java
Enhancement
___
- Added validation for party function codes in EBL documents:
* Main document supports codes: SCO, DDR, DDS, COW, COX, CS, MF, WH
* House bill of ladings supports codes: DDR, DDS, CS, MF, WH
- Implemented validation checks in EBLChecks class for both document types
- Added comprehensive unit tests to verify party function validation
- Minor formatting improvements in API request schema
___
<tr>
<td>
<details>
<summary><strong>EBLChecks.java</strong><dd><code>Add party function code validation checks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> SD-603 Update PartyFunction EBL

- booking/src/main/java/org/dcsa/conformance/standards/booking/checks/BookingChecks.java
- booking/src/main/java/org/dcsa/conformance/standards/booking/model/PersistableCarrierBooking.java
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/checks/EBLChecks.java
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/models/CarrierShippingInstructions.java
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/CarrierScenarioParameters.java
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/party/EblShipper.java
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-2c2u1e.json
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-2c2u2e.json
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-amf.json
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-clad.json
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-dg.json
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-negotiable-bl.json
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-request.json
- ebl/src/main/resources/standards/ebl/messages/ebl-api-3.0.0-soc-references.json
Bug fix, Enhancement
___
- Standardized the casing of `commoditySubReference` across multiple files.
- Updated validation logic to reflect the corrected casing.
- Adjusted JSON templates to use `commoditySubReference` consistently.
- Improved conformance checks for booking and eBL standards.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><details><summary>14 files</summary><table>
<tr>
<td><strong>BookingChecks.java</strong><dd><code>Corrected casing for `commoditySubReference` in booking checks</code></dd></td>
<td><a href="https://github.com/dcsaorg/Conformance-Gateway/pull/248/files#diff-49081d349f9f79c3b4fefee92a966e1e0cd11560093ef529cffa9df7d2991f07">+5/-5</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
<tr> …
> SD-1939-Rename commoditySubreference to commoditySubReference in Booking and Ebl

- ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/action/CarrierScenarioParametersAction.java
- ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/action/IssuanceRequestResponseAction.java
- ebl-issuance/src/main/java/org/dcsa/conformance/standards/eblissuance/party/CarrierScenarioParameters.java
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/crypto/PayloadSignerFactory.java
- pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/PintAction.java
- pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/ReceiverSupplyScenarioParametersAndStateSetupAction.java
- pint/src/main/java/org/dcsa/conformance/standards/eblinterop/action/SenderSupplyScenarioParametersAction.java
- pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/ReceiverScenarioParameters.java
- pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/SenderScenarioParameters.java
- pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/TDReceiveState.java
- pint/src/main/java/org/dcsa/conformance/standards/eblinterop/party/PintReceivingPlatform.java
- Rename some properties to clarify they are PEM encoded X.509 certs
- Improve the error handling (name the attribute that fails, an additional error check, tweak an error message)
- Eagerly validate the X.509 PEM certificate in the input method to match a similar change to EBL_ISS made by George recently.
These changes are all related to or part of SD-1940.
Enhancement, Bug fix
___
- Transitioned from public key PEM to X.509 certificate PEM handling.
- Improved error messages for certificate validation failures.
- Added validation methods for scenario parameters in PINT.
- Updated human-readable prompts for better clarity in PINT actions.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>10 …
> Bug improve issuance pint cert prompts

- pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/TDReceiveState.java
The variable should have been renamed as a part of the "Public key" -> "Cert" changes, but was overlooked until a review comment in a recent PR.
___
Bug fix, Enhancement
___
- Renamed internal attribute for clarity and consistency.
- Updated references to the renamed attribute across methods.
- Improved alignment with "Public key" to "Cert" terminology changes.
___
<tr>
<td>
<details>
<summary><strong>TDReceiveState.java</strong><dd><code>Rename and update internal attribute references</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pint/src/main/java/org/dcsa/conformance/standards/eblinterop/models/TDReceiv …
> Rename internal attribute to make it less confusing

- ebl-issuance/pom.xml
- ebl/pom.xml
- ebl/src/main/java/org/dcsa/conformance/standards/ebl/crypto/Checksums.java
We received a report in products that a supporting tool were not producing the correct checksums for TDs. Turns out that the library we were using (same as in Conformance Framework) does not produce the same checksum as the Java library listed RFC8785. This commit changes the library to use the one used in RFC8785 to avoid future cases of mismatches.
@gj0dcsa: This might affect HMMs issuance tests.
___
Enhancement
___
- Replaced JSON canonicalization library with RFC8785-approved library.
- Updated checksum computation to use the new library.
- Removed dependency on `io.setl.canonical-json` library.
- Added dependency on `io.github.erdtman.java-json-canonicalization` library.
___
<table><thead><tr><th></th><th align="left">Relevant …
> SD-1963: Use the RFC8785 approved Java library for JSON canonicalization

- cdk/pom.xml
- core/pom.xml
- pom.xml
- sandbox/pom.xml
- spring-boot/pom.xml
* Move Mockito version to dependencyManagement
Note: I did try to update WebUI libraries, because of moderate sec issue, but failed. I needed to update Angular, which I tried and worked, but even with the latest version, the dependency with issues (vite) is still vulnerable. I need to try later again, when hopefully Angular used the right version as well. It also needs Angular to go from 16 -> 19, so it needs more testing & checks.
> Update Java dependencies

- core/src/main/java/org/dcsa/conformance/core/party/ConformanceParty.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/JitScenarioListBuilder.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/JitStandard.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitGetAction.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitPortCallAction.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/action/JitPortCallServiceAction.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/checks/JitChecks.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitGetPortCallFilters.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitGetPortServiceCallFilters.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitGetTerminalCallFilters.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitGetTimestampCallFilters.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitGetType.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitSchema.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/model/JitServiceTypeSelector.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitConsumer.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitPartyHelper.java
- jit/src/main/java/org/dcsa/conformance/standards/jit/party/JitProvider.java
- jit/src/main/resources/standards/jit/messages/jit-200-port-call-service-request.json
- jit/src/main/resources/standards/jit/schemas/JIT_v2.0.0.yaml
All JIT 2.0 GET actions are covered now. But it is not checked yet if the results are okay, returned from the endpoint (like matching IDs, matching result count etc). There are still 2 issues left in Jira, where I can put that into.  
Since the `persistentMap` is not clean when every scenario starts, `flushTimestamps` is called on the SSPAction & PortCall Action. Need to fix that in a different way later.
> SD-1895 Add JIT 2.0 GET actions

- spring-boot/src/test/java/org/dcsa/conformance/springboot/ConformanceApplicationTest.java
* Sometimes, in a GitHub Actions build run, 500ms sleep is needed for any progress is measured
> SD-2053 Revert update timeout change in ConformanceApplicationTest class

- arrival-notice/src/main/java/org/dcsa/conformance/standards/an/checks/ANChecks.java
Bug fix
___
- Removed `typeCode` validation from vessel voyage checks
___
```mermaid
flowchart LR
A["validateTransport()"] --> B["Transport Validation Checks"]
B --> C["ETA Validation"]
B --> D["Port of Discharge Validation"]
B --> E["Vessel Voyages Array Validation"]
B --> F["Vessel Name Validation"]
B --> G["Carrier Voyage Number Validation"]
H["typeCode Validation"] -.-> B
style H stroke-dasharray: 5 5
style H fill:#ffcccc
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>ANChecks.java</strong><dd><code>Remove typeCode validation from transport checks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> SD-2331-Removed type code validation from vessel voyage
